
package com.alcatelsbell.cdcp.nbi.ws.irmclient;

import com.alcatelsbell.nms.util.SysProperty;
import com.alcatelsbell.nms.util.log.LogUtil;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "IrmsDataSyncWebServiceImplService", targetNamespace = NamingSpace.ns_default, wsdlLocation = "http://127.0.0.1:8080/irmsDataSyncWebService.xml")
public class IrmsDataSyncWebServiceImplService
    extends Service
{

    private final static URL IRMSDATASYNCWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(IrmsDataSyncWebServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = IrmsDataSyncWebServiceImplService.class.getResource(".");
            //url = new URL(baseUrl, "http://127.0.0.1:8080/irmsDataSyncWebService.xml");
            url = new URL(baseUrl, SysProperty.getString("cdcp.nbi.irm.url",
                    "http://10.211.106.219:6020/irm/services/irmsDataSyncWebService?wsdl"));
            LogUtil.info(IrmsDataSyncWebServiceImpl.class,"IRM URL="+url);
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8080/irmsDataSyncWebService.xml', retrying as a local file");
            logger.warning(e.getMessage());
        }
        IRMSDATASYNCWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public IrmsDataSyncWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IrmsDataSyncWebServiceImplService() {
        super(IRMSDATASYNCWEBSERVICEIMPLSERVICE_WSDL_LOCATION, new QName(NamingSpace.ns, "IrmsDataSyncWebServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns IrmsDataSyncWebServiceImpl
     */
    @WebEndpoint(name = "irmsDataSyncWebService")
    public IrmsDataSyncWebServiceImpl getIrmsDataSyncWebService() {
        return super.getPort(new QName(NamingSpace.ns, "irmsDataSyncWebService"), IrmsDataSyncWebServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IrmsDataSyncWebServiceImpl
     */
    @WebEndpoint(name = "irmsDataSyncWebService")
    public IrmsDataSyncWebServiceImpl getIrmsDataSyncWebService(WebServiceFeature... features) {
        return super.getPort(new QName(NamingSpace.ns, "irmsDataSyncWebService"), IrmsDataSyncWebServiceImpl.class, features);
    }

}
